### ISSUE TITLE
scapy.all.sniff sometimes adds 4 bytes of UDP payload

### ISSUE THREAD

**Issue by desbma** [phaethon/scapy#18] opened 2015-08-20 17:13 UTC
Under the following circumstances :
* UDP over IPv6
* UDP port around 500 (501 works too, but not 600 for example)
* UDP payload length <= 24

scapy.all.sniff incorrectly adds 4 bytes of additional data to the captured UDP payload.

Using a socket to receive the data, or capturing with Wireshark, these 4 bytes do not appear.

Here is a full test case to reproduce (test with 2 interfaces connected by a simple cable):

    #!/usr/bin/env python3

    import contextlib
    import os
    import socket
    import threading
    import unittest

    import scapy.all

    ITF_SRC = "eth6"
    ITF_DST = "eth5"
    IP_SRC = "2014::1"
    IP_DST = "2015::1"
    UDP_PORT = 500

    class SniffThread(threading.Thread):

      def __init__(self, *args, **kwargs):
        self.args = args
        self.kwargs = kwargs
        self.received = []
        super().__init__()

      def run(self):
        self.received.extend(scapy.all.sniff(*self.args, **self.kwargs))

    class TestScapyUdpCaptureIssue(unittest.TestCase):

      def test_captureSocket(self):
        for udp_payload_size in (25, 24):
          # build udp frame
          eth = scapy.all.Ether(src=scapy.all.get_if_hwaddr(ITF_SRC),
                                dst=scapy.all.get_if_hwaddr(ITF_DST))
          ip = scapy.all.IPv6(src=IP_SRC,
                              dst=IP_DST)
          udp = scapy.all.UDP(sport=UDP_PORT, dport=UDP_PORT)
          payload_udp = os.urandom(udp_payload_size)
          frame = eth / ip / udp / payload_udp

          # listen for future response
          with contextlib.closing(socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)) as sckt_rec:
            sckt_rec.settimeout(1)
            sckt_rec.bind((IP_DST, UDP_PORT))

            # send frame
            scapy.all.sendp(frame, iface=ITF_SRC, verbose=False)

            # check response
            try:
              received, address = sckt_rec.recvfrom(16384)
            except socket.timeout as e:
              self.fail("%s: %s (udp_payload_size = %u)" % (e.__class__.__name__, e, udp_payload_size))
            self.assertEqual(address, (IP_SRC, UDP_PORT, 0, 0), "udp_payload_size = %u" % (udp_payload_size))
            self.assertSequenceEqual(received, payload_udp, "udp_payload_size = %u" % (udp_payload_size))

      def test_captureSniff(self):
        for udp_payload_size in (25, 24):
          # build udp frame
          eth = scapy.all.Ether(src=scapy.all.get_if_hwaddr(ITF_SRC),
                                dst=scapy.all.get_if_hwaddr(ITF_DST))
          ip = scapy.all.IPv6(src=IP_SRC,
                              dst=IP_DST)
          udp = scapy.all.UDP(sport=UDP_PORT, dport=UDP_PORT)
          payload_udp = os.urandom(udp_payload_size)
          frame = eth / ip / udp / payload_udp

          # listen for future response
          ipv6nh_codes = dict(zip(scapy.all.ipv6nh.values(), scapy.all.ipv6nh.keys()))
          sniff_thread = SniffThread(timeout=1,
                                     iface=ITF_DST,
                                     lfilter=lambda x: x[scapy.all.IPv6].nh not in (ipv6nh_codes["ICMPv6"],
                                                                                    ipv6nh_codes["Hop-by-Hop Option Header"]))
          sniff_thread.start()

          # send frame
          scapy.all.sendp(frame, iface=ITF_SRC, verbose=False)
          sniff_thread.join()

          # build expected response
          expected_eth = scapy.all.Ether(src=scapy.all.get_if_hwaddr(ITF_SRC),
                                         dst=scapy.all.get_if_hwaddr(ITF_DST))
          expected_ip = scapy.all.IPv6(src=IP_SRC, dst=IP_DST)
          expected_udp = scapy.all.UDP(sport=UDP_PORT, dport=UDP_PORT)
          expected = expected_eth / expected_ip / expected_udp / payload_udp

          # check response
          self.assertEqual(len(sniff_thread.received), 1, "udp_payload_size = %u" % (udp_payload_size))  # fails if udp_payload_size == 24
          self.assertSequenceEqual(bytes(sniff_thread.received[0]),
                                   bytes(expected),
                                   "udp_payload_size = %u" % (udp_payload_size))

    if __name__ == "__main__":
        unittest.main()

Context :
* Ubuntu 14.04
* Python 3.4
* Scapy v0.13 from this repo.

**Comment by phaethon** [comment] 2015-08-21 20:11
Issue confirmed. Actually I did not need two interfaces - using the same interface and address for both src and dst works ok, too.

**Comment by phaethon** [comment] 2015-08-21 20:43
I see failures only with port 500. I could not reproduce with port 501.
If I switch off isakmp layer, I cannot reproduce failure, so it seems isakmp module is messing with the payload. Will investigate isakmp

**Comment by desbma** [comment] 2015-08-24 07:57
You are right by adding a retry loop, it only fails constantly for port 500.

**Comment by phaethon** [comment] 2015-08-25 16:17
When scapy sees communication on UDP port 500 it assumes it is isakmp and tries to treat it as such. Just for one packet - it is quite hard to distinguish isakmp with invalid payload (or no payload) from random bytes. There is post_build method for ISAKMP class, that adds length to ISAKMP header if it finds none. This is what happens in this case.
Issue has no trivial fix (suggestions - welcome), and would possibly require some compromises. At the same time, practical impact of the issue is limited, as normal ISAKMP traffic would be dissected fine, and there is small probability somebody will often need different behaviour. Even then it can be done with a simple workaround - disabling ISAKMP layer.
Marking it as won't fix for now.

**Closed by phaethon** 2015-08-25 16:17 UTC
Labels: bug

**Comment by desbma** [comment] 2015-08-25 16:40
Thanks for taking the time to analyze this issue.

> There is a post_build method for ISAKMP class, that adds length to ISAKMP header if it finds none.

I understand the rational for this behavior when one want to explicitly build an ISAKMP packet. However I don't understand why this method is invoked **automatically** at **capture** time.

This prevents scapy from being used reliably to analyze traffic. 

I believe manipulating invalid or unexpected packets to observe how a device/network reacts to it is one of the main use cases of Scapy.

**Comment by phaethon** [comment] 2015-08-25 17:34
I agree, this may not match your expectations, but you have at least two workarounds:

1. Switch off isakmp module
2. Use RawPcapReader if you are mainly interested in actual bytes; optionally, dissecting specific packets

I am still open for discussion on improvements, and then opening corresponding enhancement issue. I see at least three possible directions:

1. Identifying plugins, which may change packet bytes, and let user switch them all off, so that you could be sure, no byte has been changed.
2. Changes to packet dissection code, so that nothing is ever changed in captured bytes unless explicitly asked (this is probably what you meant with 'reliably').
3. Maybe some clever ideas to improve isakmp.

**Comment by desbma** [comment] 2015-08-26 08:17
> Changes to packet dissection code, so that nothing is ever changed in captured bytes unless explicitly asked (this is probably what you meant with 'reliably').

This seems the more logical approach to me. Actually I don't understand how someone would want to enable a behavior to alter captured packets without knowing for sure how and if they have been modified.

However, I'm not familiar with the codebase, and don't know how much work it would take.

**Comment by phaethon** [comment] 2015-08-31 07:15
I am not the author, but from what I see in the code, initial design of scapy is focused on packet crafting. From that perspective fixing the packet, so that it is valid for the specified protocol, does not sound unreasonable. Also, this is why I refuse to classify this as a bug.
Changing the behaviour, to guarantee that never anything is changed would require complete code review. At the same time - there are reasonable workarounds and I still don't see practical example from real life, where this would make a significant problem.
