### ISSUE TITLE
RandIP() (at least) behaviour change due to code relying on old-style classes

### ISSUE THREAD

**Issue by ppietikainen** [phaethon/scapy#13] opened 2015-07-15 06:14 UTC
This may be more ugly than seems at a first glance:

```
Welcome to Scapy (2.2.0-dev)
>>> print(RandIP())
251.239.113.24
```
vs. 

```
Welcome to Scapy (3.0.0)
>>> print(RandIP())
<RandIP>
```
which is explained by the use of old-style Python 2 classes and `__getattr__`in VolatileValue magically fixing things up. Easily fixed by adding a
```python
def __str__(self): 
   return self._fix()
````
to class VolatileValue, but then there's int(RandShort()) etc.

Quickly grepping around for previously old-style classes with `__getattr__`   seems like there might be other places where this may cause mysterious bugs...

**Comment by phaethon** [comment] 2015-07-15 12:07
Thanks for noticing. Will check the code for __getattr__ usage.

**Comment by phaethon** [comment] 2015-07-15 15:54
This was tricky, but I fixed `__getattr__` usage in volatile module for cases when `__int__`, `__str__`, `__repr__`, `__index__` could be called. Comments on other special methods to be included are welcome. Please, check latest git version.

`__cmp__` is not ported, but I am not sure if the code uses it.

**Comment by ppietikainen** [comment] 2015-07-24 10:18
My code started working just fine :-) For other uses, yes, it's tricky to find out.  E.g. Automaton looks like it could be a candidate:

```python
{'BEGIN': <function ATMT.state.<locals>.deco.<locals>.state_wrapper at 0x7f4bcaf2b158>, 'END': <function ATMT.state.<locals>.deco.<locals>.state_wrapper at 0x7f4bcaf2b378>}
<session[HelloWorld]: TCP:0 UDP:0 ICMP:0 Other:0>

vs. the previous 

{'BEGIN': <function BEGIN_wrapper at 0x7f48efeaa848>, 'END': <function END_wrapper at 0x7f48efeaaa28>}
[]
```
(printing "states" and "packets" from the HelloWorld example at https://bitbucket.org/secdev/scapy/wiki/doc/Automata ). 

X509Cert() ! (or probably the ASN1 stuff within).

Actually, a nice test seems to be:

```python
from scapy.all import *
s = dir()
import inspect
import sys

for f in s:
  o = getattr(sys.modules[__name__], f)
  if inspect.isclass(o):
    try:
      o()
    except TypeError:
      pass
    except Exception as e:
      print ((f, e))
```

which probably finds problems unrelated to this bug as well :-)

**Comment by phaethon** [comment] 2015-07-24 14:45
Please, check X509Cert. It should be working now. I will have a look at Automaton later.

**Comment by ppietikainen** [comment] 2015-07-24 17:58
Seems to work. https://github.com/ppietikainen/scapy has some random fixes-in-progress/testing you may want to check out, will test a bit before sending a proper pull request but feel free to merge.

Left to figure out (maybe not problems :-)):

('DHCPv6_am', TypeError('ord() expected string of length 1, but int found',))
('MetaVolatile', TypeError('type() takes 1 or 3 arguments',))
('RandDHCPOptions', AttributeError("'dict_values' object has no attribute 'remove'",))
('TermSink', FileNotFoundError(2, "No such file or directory: 'xterm'"))

**Comment by phaethon** [comment] 2015-07-30 13:58
I checked Automaton. It is not the same story. It was not not about getattr, but assigning __name__ for wrapped functions. I fixed it by changing assignment to __qualname__, but it still looks differently than on python 2.x because of differences in built-in __repr__ for functions. It adds module name in front of the function name, but I am fine with that and don't see necessity for change.
At least all regression tests work, so I assume no big issues there. I, also, fixed graph for automaton. 

I looked at your changes, and all of them seem fine. If you are going to create a pull request I will wait for that.

Now I am going to check the list of 4 in your last comment.

**Comment by phaethon** [comment] 2015-07-31 06:29
- DHCPv6_am - fixed ord issue

- MetaVolatile - is supposed to be private, so I renamed it to _MetaVolatile; in any case it takes as it says 1 or 3 arguments as a descendant of type

- RandDHCPOptions - fixed

- TermSink - you need to have xterm installed on path. Command name is hardwired into code. Could be made into configurable value if needed, but did not do that yet.

Thanks for identifying issues!

**Comment by phaethon** [comment] 2015-11-19 20:52
Closing this for now, as specific identified issues have been fixed

**Closed by phaethon** 2015-11-19 20:52 UTC
