### ISSUE TITLE
Scapy3 on Windows7

### ISSUE THREAD

**Issue by chezach** [phaethon/scapy#50] opened 2015-12-20 20:21 UTC
I am trying to explore scapy3 on a Windows7 platform and was successful with installing the required packages. I am a beginner in this tool and I am trying a few examples from the documentation page. I understand that scapy3 on a Windows platform is still under testing, but here in my organisation we use Python3.4 on a Windows platform and hence the need to try this tool on a Windows platform. To start with a very basic step, I was able to create a IP packet with some destination address, but when I execute the show() command, I get the following error.

"

In [9]: IP().show()
    ←[0m###[←[0m ←[31m←[1mIP←[0m ←[0m]###←[0m
    ←[34mversion←[0m←[0m=←[0m ←[35m4←[0m
    ←[34mihl←[0m←[0m=←[0m ←[35mNone←[0m
    ←[34mtos←[0m←[0m=←[0m ←[35m0x0←[0m
    ←[34mlen←[0m←[0m=←[0m ←[35mNone←[0m
    ←[34mid←[0m←[0m=←[0m ←[35m1←[0m
    ←[34mflags←[0m←[0m=←[0m ←[35m←[0m
    ←[34mfrag←[0m←[0m=←[0m ←[35m0←[0m
    ←[34mttl←[0m←[0m=←[0m ←[35m64←[0m
    ←[34mproto←[0m←[0m=←[0m ←[35mip←[0m
    ←[34mchksum←[0m←[0m=←[0m ←[35mNone←[0m
    ←[34m←[4m←[1msrc←[0m←[0m=←[0m ←[35m←[4m←[1m0.0.0.0←[0m
    ←[34m←[4m←[1mdst←[0m←[0m=←[0m ←[35m←[4m←[1m127.0.0.1←[0m
    \←[34moptions←[0m\

In [10]:"
I see that this could be some kind of encoding / decoding issue. Have anybody tried this and come across this issue? Any help is much appreciated.

**Comment by syakesaba** [comment] 2015-12-26 23:03
try
 conf.color_theme = NoTheme()

**Comment by phaethon** [comment] 2015-12-28 12:36
How did you install python (and seems you have ipython, too)? I recommend you Anaconda distribution. This will be easier than to get into details about configuration.
Windows 7 is not fully supported because scapy3k currently uses certain Powershell function available only starting from Windows 8 (for detecting network interfaces and routing table).

**Comment by fedorch** [comment] 2016-01-03 04:21
Hi!
Is it possible to manualy setup **interface_list** and **routes** lists to run scapy on some PC under Windows 7?
I'm trying to update PowerShell 2.0 on my Windows 7 SP1 to version 3.0, then to version 4.0, and then to version 5.0. https://www.linkedin.com/pulse/getting-powershell-5-running-windows-7-server-2008-r2-darwin-sanoy
But even PowerShell version 5.0 (on Windows 7) does not understand **Get-NetAdapter** and **Get-NetRoute** commands :-(((

**Comment by fedorch** [comment] 2016-01-04 00:59
Hi, again!
Look at **winpcapy** to free **scapy3k** from depending on the PowerShell.
https://code.google.com/p/winpcapy/
It works just fine! Don't have any dependencies. The only requirement is that the WinPcap is installed. It uses **wpcap.dll**
But winpcapy so low-level compare to scapy. It will be great if **scapy3k** will work on any version of Windows where WinPcap is installed.

**Comment by phaethon** [comment] 2016-01-04 08:59
I am using winpcapy already, but it does not do every thing that is needed. Powershell is used to get list of interfaces (with descriptive names) and routes. winpcapy does not provide that, or if I am mistaken explain me a way to do it.

On Windows7 you can set corresponding data structures manually and use scapy. If interested to investigate I can send a more detailed info.

**Comment by fedorch** [comment] 2016-01-04 12:15
winpcap provide the following information about interfaces (I don't know is this enough):
```
1. b'\\Device\\NPF_{004CAEAB-7CC9-49A9-9524-7DCFCA301FC3}'
   (b'Sun')

2. b'\\Device\\NPF_{BD133C50-7E85-4EA5-809C-B818E9370B38}'
   (b'Realtek RTL8139/810x Family Fast Ethernet NIC                                   ')

3. b'\\Device\\NPF_{09078F9D-2A19-4282-AAFD-16012120883D}'
   (b'Realtek PCIe GBE Family Controller')
```
Some information about the routes can be obtained by **route print** command:

![2016-01-04_14-42-53](https://cloud.githubusercontent.com/assets/6808299/12089340/d6bedc7c-b2f4-11e5-9a9f-bf541a283d3b.png)

**Comment by phaethon** [comment] 2016-01-04 12:26
It is possible to create a script using netstat and ifconfig, parsing their text output, but it is really not the way I would like to go in the future. Probably majority of Windows 7 users will go to Windows 10 within the 1 year upgrade opportunity.
If you submit a patch which works with Windows 7 I will integrate it.

**Comment by fedorch** [comment] 2016-01-04 12:46
> On Windows7 you can set corresponding data structures manually and use scapy. If interested to investigate I can send a more detailed info.

Can you provide me additional information on how to filled lists *interface_list* and *routes* should look like?

**Comment by phaethon** [comment] 2016-01-04 12:53
See functions `get_windows_if_list` and `read_routes` in scapy/arch/windows/__init__.py
routes is a list created by these statements ```routes.append((dest, mask, gw, iface, addr))```
List of interfaces is created using these:
```
        if name == 'Name':
            if current_interface:
                interface_list.append(current_interface)
            current_interface = {}
            current_interface['name'] = value
        elif name == 'InterfaceIndex':
            current_interface['win_index'] = int(value)
        elif name == 'InterfaceDescription':
            current_interface['description'] = value
        elif name == 'InterfaceGuid':
            current_interface['guid'] = value
        elif name == 'MacAddress':
            current_interface['mac'] = ':'.join([ j for j in value.split('-')])
```

**Comment by n1nj4sec** [comment] 2016-01-08 08:14
Hello, I made a patch to support windows 7 but for the official scapy branch. I think it could be integrated with a few modifications ;) the link to happiness : https://bitbucket.org/secdev/scapy/pull-requests/158

**Comment by gparent** [comment] 2016-02-26 16:32
Is there any information about whether this patch can be integrated, and if not, why, for those of us interested in getting  Windows 7 to work?

**Comment by gparent** [comment] 2016-02-26 16:38
I'm getting errors related to get_windows_if_list even though I don't care about capturing at all, is there a way to completely avoid this code in Windows 7?

I want to run this snippet:

```
from scapy.all import *

with PcapReader('cap.pcap') as pcap_reader:
    for pkt in pcap_reader:
        print('Packet!')
```

**Comment by n1nj4sec** [comment] 2016-02-26 16:39
This patch (with also xp support) has been integrated into the original
scapy's master https://github.com/secdev/scapy
Le 26 févr. 2016 17:32, "gp" <notifications@github.com> a écrit :
>
> Is there any information about whether this patch can be integrated, and
if not, why, for those of us interested in getting Windows 7 to work?

**Comment by gparent** [comment] 2016-02-26 18:55
I see, so it requires a bit of manual work for this repo. Unfortunately I cannot use secdev Scapy as I do not think it supports Python3. Thank you for chiming in,

**Comment by sysengkm** [comment] 2016-02-26 21:45
This works as an alternative interface detection method that supports Windows 7 and later, haven't tested earlier. It will substitute the names and fixup the semicolons so that Win32_NetworkAdapter results match the Get-NetAdapter results.  It might be good to run the alternate based on the results of (Get-WmiObject -Class Win32_OperatingSystem).Version so the fixup can be retired later.

in `__init__.py,` modify the function `get_windows_if_list()`

Change the ps = sp.Popen line that runs Get-NetAdapter to:
`ps = sp.Popen(['powershell', '-NoProfile', 'Get-WMIObject -class Win32_NetworkAdapter', '|', 'select Name, @{Name="InterfaceIndex";Expression={$_.Index}}, @{Name="InterfaceDescription";Expression={$_.Description}},@{Name="InterfaceGuid";Expression={$_.GUID}}, @{Name="MacAddress";Expression={$_.MacAddress.Replace(":","-")}}', '|', 'fl'], stdout = sp.PIPE, universal_newlines = True)`

**Comment by gparent** [comment] 2016-02-27 07:14
I can confirm this worked on Windows 7. Thank you.

**Comment by phaethon** [comment] 2016-03-05 20:31
Anybody willing to create pull request for Windows 7 compatibility?

**Comment by phaethon** [comment] 2016-03-12 08:07
Can you try with the latest commit if your issues are fixed?

**Comment by gparent** [comment] 2016-03-14 18:35
@phaethon If you're asking me, I just tried the current master and I get the same error as before (too many values to unpack (expected 2).

With the modified `get_windows_if_list()` function, the snippet I posted above runs normally.

**Comment by sysengkm** [comment] 2016-03-14 22:05
Weird, I just downloaded a fresh copy and tested out fine on windows 7 64 bit. Can you confirm whether or not the get_windows_if_list() contains the Get-WMIObject code in your copy? 
Here is the first few line of code in my freshly unzipped copy:

    ps = sp.Popen(['powershell', '-NoProfile', 'Get-WMIObject -class Win32_NetworkAdapter', '|', 'select Name, @{Name="InterfaceIndex";Expression={$_.Index}}, @{Name="InterfaceDescription";Expression={$_.Description}},@{Name="InterfaceGuid";Expression={$_.GUID}}, @{Name="MacAddress";Expression={$_.MacAddress.Replace(":","-")}} | where InterfaceGuid -ne $null', '|', 'fl'], stdout = sp.PIPE, universal_newlines = True)
`

**Comment by gparent** [comment] 2016-03-15 14:27
Correct. That code doesn't work for either live or file captures. The previous snippet worked at least for file captures (but I did not try interface captures).

**Comment by phaethon** [comment] 2016-04-11 14:54
There have been some changes, which affect Windows 7 compatibility. I am closing this issue for now, as it is very broad and possibly has outdated comments. Please, add new issue if there still are issues with latest git version and Windows 7

**Closed by phaethon** 2016-04-11 14:54 UTC
